services:
  longvu:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6789:6789
    volumes:
      - type: volume
        source: app
        target: /workspace/app
      - ./my_ext:/workspace/app/my_ext
      - ../storage:/workspace/app/storage
      - nfs_data:/workspace/app/checkpoints
    # command: tail -f /dev/null
    privileged: true
    environment:
      - HF_TOKEN=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
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    shm_size: 1g

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: ./app
      o: bind
  nfs_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=101.100.182.29,rw,nolock,fsc
      device: :/volume1/workspace/longvu/checkpoints