services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - selenium

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  longvu_pg:
    build:
      context: ../longvu_pg
      dockerfile: Dockerfile
    volumes:
      - ../storage:/workspace/app/storage
      - nfs_data:/workspace/app/checkpoints
      - ../longvu_pg/my_ext:/workspace/app/my_ext
    # command: tail -f /dev/null
    ports:
      - 6789:6789
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    healthcheck:
      disable: true

volumes:
  nfs_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=101.100.182.29,rw,nolock,fsc
      device: :/volume1/workspace/longvu/checkpoints