services:
  rails-app:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    env_file:
      - .env.tmp

    # https://serversideup.net/how-to-get-ssh-to-work-with-1password-docker-desktop-macos-within-a-container/
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock

    volumes:
      - ../..:/workspaces:cached
      - ${HOME}/.ssh:/.ssh:ro
      - ${HOME}/.ssh/known_hosts:/.ssh/known_hosts:rw
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
#    depends_on:
#    - selenium

#  selenium:
#    image: selenium/standalone-chromium
#    restart: unless-stopped

#  longvu_pg:
#    build:
#      context: ../longvu_pg
#      dockerfile: Dockerfile
#    volumes:
#      - ../storage:/workspace/app/storage
#      - nfs_data:/workspace/app/checkpoints
#      - ../longvu_pg/my_ext:/workspace/app/my_ext
    # command: tail -f /dev/null
#    ports:
#      - 6789:6789
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]
#    healthcheck:
#     disable: true

#volumes:
#  nfs_data:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=101.100.182.29,rw,nolock,fsc
#      device: :/volume1/workspace/longvu/checkpoints